### ISSUE TITLE
Add File upload? and other questions

### ISSUE THREAD

**Issue by mikagrand** [vlio20/angular-material-form-builder#12]
Hello, first for most i want to say you done a very good job.
- Now i want to know how to add File "upload field" ?
- And also how to add submit button ?
- And how i can customize error message ?
- And how to add 1,2,3 or 4 fields inline ?
And in a demo there are only few types of fields, i want to know if you can give me a "complete Json Parameters".

Thank

**Comment by vlio20** [comment]
For all of this I would say that you have to dig-in into the code. This repo has the building blocks and all the examples - rest of it is on you.

You are welcome to submit PRs. If you have specific technical questions - shoot!
