### ISSUE TITLE
Support for Angular 1.8.x and modern tools

### ISSUE THREAD

**Issue by lamuertepeluda** [vlio20/angular-material-form-builder#15]
Hi @vlio20 ,

first of all, thank you for this library. We have forked it some years ago to add some changes, and we are using it in our project. Nowe we needed to refactor and update the whole software, so after moving from Angular 1.5.x to 1.8.x, we needed also to update this library, since we were getting some runtime errors.  

In fact, in our project we are still using AngularJS and we are not yet able to get rid of it, moving to a more modern framework. However we moved our full toolchain, ditching yeoman, bower, grunt and other old dusty stuff like that.

Therefore, I made a full refactor of your repository here in this branch https://github.com/xcally/angular-material-form-builder/tree/modern-js

There are several major changes. Here's the list:
 
* support for Angular 1.8.x (but I did not mind backward compatibility)
* refactor of all components using ES6 classes and separating controller files from directive files
* addition of two more items, `label` and `agreement`, which were useful for our use case
* use webpack 5 + babel instead of gulp-yeoman build toolchain
* changed a bit the directory structure, separating the demo app from the library.
* library files are also now correctly identified in package.json
* we set version number to 1.0.0

I basically only need to setup again the tests environment, and I'd like to do it with Jest.  

That said, I tried this new library version in both the demo included and in our project and it seems working fine.

We'd like to publish this package on npm, since yours was only available in bower, which will be soon discontinued, not mentioning the troubles with hidden dependency packages.

*Do you mind if we take care of publishing this new version of the library on npm from our fork*? We'd of course cite you as the original author. Otherwise let me know if you prefer to have a look at the changes first and keep maintaining this package and also take care of the npm publishing.

In the latter case we can easily make PRs.

Sorry for the long text 😅 , looking forward for your reply.

**Comment by vlio20** [comment]
I have a different proposition, would you mind If I will give you access to this repo?

**Comment by lamuertepeluda** [comment]
sure, no problem

**Comment by lamuertepeluda** [comment]
@vlio20 I ported all my changes and released a new version 1.0.0 here on Github.  
What about npm publishing? May I take care of that, using our account, or do you prefer using a npm account of yours?

**Comment by vlio20** [comment]
@lamuertepeluda yes, go ahead, use your account.
