### ISSUE TITLE
Reorder questions and delete them

### ISSUE THREAD

**Issue by Misiu** [vlio20/angular-material-form-builder#2]
Hi there, first of all thank You for such great component.
I'm planning to use it, but there are two things I think are missing - there should be an option to reorder questions and delete them.
This way form builder would be complete.

**Comment by vlio20** [comment]
Hi @Misiu,
You can reorder options, if you want to implement reordering you can do it in your own application. I did it in mine. It is very simple thing to do with Angular. Here is a screen shot:
http://prntscr.com/9vhh9l

Nevertheless. I will add it gladly but it would be great if you could supply me a mock.

**Comment by Misiu** [comment]
HI @vlio20 I'd like to create PR but I'm just starting with Angular so there is much to learn for me before I'll create something as advanced as Your component.
I've searched a bit and found this: http://mwasiluk.github.io/angular-surveys/
Maybe you could add something like this?
When hovering over question icon to delete would show and then after click and confirm question would be deleted. Same with moving questions. On hover there could be an icon that would allow to move questions.

**Comment by vlio20** [comment]
ok, I will try to do it in my next release - probably in this weekend.

**Comment by Misiu** [comment]
@vlio20 awesome news :)

**Comment by vlio20** [comment]
@Misiu, feel free to give a :star:

**Comment by Misiu** [comment]
thank You for such fast commit :)
