### ISSUE TITLE
Allow to collapse/expand questions and drag-reorder

### ISSUE THREAD

**Issue by Misiu** [vlio20/angular-material-form-builder#3]
I've noticed when having a lot of questions it is hard to navigate.
Maybe You could use something like accordion-panel (expand-collapse) for each question. This way it would be possible to collapse all question and show only their title, like in material design docs (https://material.angularjs.org/latest/demo/content - just click show code button, then content expands)
Having this it would be easy to add drag reorder like this: http://a5hik.github.io/ng-sortable/#/kanban

**Comment by vlio20** [comment]
@misiu , this a very specific request. There might be users that would not want this type of UX. You can use the form-item and build your own user experience. I will gladly help you with that.

**Comment by Misiu** [comment]
@vlio20 I have issue with code that is based on Your form builder. I'm trying to build something similar, but I'd like to show one question at a time. Could You please take a look: http://stackoverflow.com/questions/35504567/angular-material-controller-mdradiogroup-required-by-directive-mdradiobutt

**Comment by vlio20** [comment]
@Misiu, I have looked in your code but couldn't find anything helpful. Sorry
