### ISSUE TITLE
Elements predefined in json 

### ISSUE THREAD

**Issue by kuncevich** [vlio20/angular-material-form-builder#4]
Just trying to figure out If I have json predefined in file or somewhere in my `html/controller/etc` how to generate material elements this way. First thing I renamed `<pre>{{main.form | json}}</pre>` into`<textarea>{{main.form | json}}</textarea>` but if I modify json in textarea the material elements did't reflect the changes so then I modified the main.controller like that:

```
  var json = {
    "items": [
        {
        "type": "textarea",
        "props": {
            "title": "",
            "helpText": ""
        },
        "config": {
            "required": false,
            "placeholder": "From Json"
        },
        "value": ""
        }
    ]
    };

  /** @ngInject */
  function MainController() {
    vm = this;
    vm.form = json;
  }
```

But seams to be form-builder not working this way. Any thoughts how to make it working?

**Comment by vlio20** [comment]
Hey @kuncevich , can you please provide a plunker? it would be much easier.

thanks

**Comment by kuncevich** [comment]
@vlio20 do not have a plunker but have `gulp build` output https://www.dropbox.com/s/8ou862b2000jrpv/dist.zip?dl=0 if that is OK

**Comment by vlio20** [comment]
@kuncevich It is hard to work with the build output. It would be better to get the src files if you don't want to create a plunker.

**Comment by kuncevich** [comment]
@vlio20 yeah I see. Can you try this one https://github.com/kuncevich/angular-material-form-builder I just made this single commit

**Comment by kuncevich** [comment]
Btw I think I figure out the issue. My json wasn't quite right

**Comment by vlio20** [comment]
@kuncevich, There is no 2 way db between the textarea you have created to the right side. 
I think there is no need for this type of behaviour. If you need it, pls make a pull request and I will see how it effects the component.
